import { PartData } from './types';

export const PART_1_DATA: PartData = {
  id: 'part-1',
  partNumber: 1,
  titleEs: 'Categorías gramaticales — Ejercicios 7º grado / 1º ESO',
  titleHy: 'Քերականական կարգեր — Վարժություններ 7-րդ դասարան / 1º ESO',
  subtitleEs: 'Práctica interactiva completa de las 7 categorías gramaticales con traducción al clic y respuestas.',
  subtitleHy: '7 քերականական կարգերի ամբողջական ինտերակտիվ պրակտիկա՝ սեղմումով հայերեն թարգմանությամբ և պատասխաններով։',
  sections: [
    {
      id: 'p1-s1',
      sectionNumber: 1,
      titleEs: '1. Identifica la categoría',
      titleHy: '1. Որոշի՛ր քերականական կարգը',
      descriptionEs: 'Elige la opción correcta para cada una de las siguientes palabras.',
      descriptionHy: 'Ընտրի՛ր ճիշտ տարբերակը հետևյալ բառերից յուրաքանչյուրի համար։',
      questions: [
        {
          id: 'p1-q1',
          number: 1,
          type: 'multiple-choice',
          instructionEs: '¿Qué categoría gramatical es esta palabra?',
          instructionHy: 'Ի՞նչ քերականական կարգի բառ է։',
          sentenceEs: 'perro',
          sentenceHy: 'շուն',
          options: [
            { key: 'a', labelEs: 'verbo', labelHy: 'բայ' },
            { key: 'b', labelEs: 'sustantivo', labelHy: 'գոյական' },
            { key: 'c', labelEs: 'adverbio', labelHy: 'մակբայ' },
            { key: 'd', labelEs: 'pronombre', labelHy: 'դերանուն' },
          ],
          correctOptionKey: 'b',
          correctAnswerText: 'b) sustantivo',
          correctAnswerHy: 'գոյական',
          explanationEs: '«Perro» nombra a un animal, por lo tanto es un sustantivo.',
          explanationHy: '«Perro»-ն անվանում է կենդանուն, ուստի գոյական է։',
        },
        {
          id: 'p1-q2',
          number: 2,
          type: 'multiple-choice',
          instructionEs: '¿Qué categoría es la palabra destacada?',
          instructionHy: 'Ի՞նչ քերականական կարգի է առանձնացված բառը։',
          sentenceEs: 'rápido en «un coche rápido»',
          sentenceHy: 'rápido-ն «արագ մեքենա» արտահայտության մեջ',
          options: [
            { key: 'a', labelEs: 'adjetivo', labelHy: 'ածական' },
            { key: 'b', labelEs: 'verbo', labelHy: 'բայ' },
            { key: 'c', labelEs: 'sustantivo', labelHy: 'գոյական' },
            { key: 'd', labelEs: 'nexo', labelHy: 'կապակցիչ' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) adjetivo',
          correctAnswerHy: 'ածական',
          explanationEs: '«Rápido» describe una cualidad del sustantivo «coche», por lo que actúa como adjetivo.',
          explanationHy: '«Rápido»-ն նկարագրում է «coche» (մեքենա) գոյականի հատկանիշը, ուստի ածական է։',
        },
        {
          id: 'p1-q3',
          number: 3,
          type: 'multiple-choice',
          instructionEs: '¿Qué categoría gramatical es esta forma?',
          instructionHy: 'Ի՞նչ քերականական կարգ է այս ձևը։',
          sentenceEs: 'corremos',
          sentenceHy: 'մենք վազում ենք',
          options: [
            { key: 'a', labelEs: 'determinante', labelHy: 'որոշիչ' },
            { key: 'b', labelEs: 'verbo', labelHy: 'բայ' },
            { key: 'c', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'd', labelEs: 'adverbio', labelHy: 'մակբայ' },
          ],
          correctOptionKey: 'b',
          correctAnswerText: 'b) verbo',
          correctAnswerHy: 'բայ',
          explanationEs: '«Corremos» expresa una acción (primera persona del plural del verbo correr).',
          explanationHy: '«Corremos»-ն արտահայտում է գործողություն (correr բայի ներկա ժամանակի 1-ին դեմք հոգնակի)։',
        },
        {
          id: 'p1-q4',
          number: 4,
          type: 'multiple-choice',
          instructionEs: '¿Qué categoría gramatical es esta palabra?',
          instructionHy: 'Ի՞նչ քերականական կարգ է այս բառը։',
          sentenceEs: 'ayer',
          sentenceHy: 'երեկ',
          options: [
            { key: 'a', labelEs: 'adverbio', labelHy: 'մակբայ' },
            { key: 'b', labelEs: 'sustantivo', labelHy: 'գոյական' },
            { key: 'c', labelEs: 'adjetivo', labelHy: 'ածական' },
            { key: 'd', labelEs: 'nexo', labelHy: 'կապակցիչ' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) adverbio',
          correctAnswerHy: 'մակբայ (ժամանակի)',
          explanationEs: '«Ayer» es un adverbio de tiempo que indica cuándo ocurre una acción.',
          explanationHy: '«Ayer»-ը ժամանակի մակբայ է, ցույց է տալիս գործողության կատարման ժամանակը։',
        },
        {
          id: 'p1-q5',
          number: 5,
          type: 'multiple-choice',
          instructionEs: '¿Qué categoría gramatical es esta palabra?',
          instructionHy: 'Ի՞նչ քերականական կարգ է այս բառը։',
          sentenceEs: 'pero',
          sentenceHy: 'բայց',
          options: [
            { key: 'a', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'b', labelEs: 'verbo', labelHy: 'բայ' },
            { key: 'c', labelEs: 'nexo', labelHy: 'կապակցիչ / շաղկապ' },
            { key: 'd', labelEs: 'determinante', labelHy: 'որոշիչ' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) nexo',
          correctAnswerHy: 'կապակցիչ (շաղկապ)',
          explanationEs: '«Pero» es una conjunción adversativa (nexo) que une oraciones o ideas contrapuestas.',
          explanationHy: '«Pero»-ն հակադրական շաղկապ (nexo) է, որը կապում է երկու նախադասություն կամ հակադիր միտք։',
        },
        {
          id: 'p1-q6',
          number: 6,
          type: 'multiple-choice',
          instructionEs: '¿Qué categoría gramatical es esta palabra?',
          instructionHy: 'Ի՞նչ քերականական կարգ է այս բառը։',
          sentenceEs: 'ella',
          sentenceHy: 'նա (իգական)',
          options: [
            { key: 'a', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'b', labelEs: 'sustantivo', labelHy: 'գոյական' },
            { key: 'c', labelEs: 'adjetivo', labelHy: 'ածական' },
            { key: 'd', labelEs: 'verbo', labelHy: 'բայ' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) pronombre',
          correctAnswerHy: 'դերանուն',
          explanationEs: '«Ella» es un pronombre personal que sustituye a un sustantivo femenino.',
          explanationHy: '«Ella»-ն անձնական դերանուն է, որը փոխարինում է իգական սեռի գոյականին։',
        },
        {
          id: 'p1-q7',
          number: 7,
          type: 'multiple-choice',
          instructionEs: '¿Qué función cumple la palabra destacada?',
          instructionHy: 'Ի՞նչ դեր է կատարում ընդգծված բառը։',
          sentenceEs: 'mi en «mi mochila»',
          sentenceHy: 'mi-ն «իմ ուսապարկը» արտահայտության մեջ',
          options: [
            { key: 'a', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'b', labelEs: 'adverbio', labelHy: 'մակբայ' },
            { key: 'c', labelEs: 'determinante', labelHy: 'որոշիչ' },
            { key: 'd', labelEs: 'verbo', labelHy: 'բայ' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) determinante',
          correctAnswerHy: 'որոշիչ (ստացական)',
          explanationEs: '«Mi» acompaña al sustantivo «mochila» indicando posesión, por lo que es un determinante posesivo.',
          explanationHy: '«Mi»-ն ուղեկցում է «mochila» (պայուսակ) գոյականին՝ ցույց տալով պատկանելություն, ուստի ստացական որոշիչ է։',
        },
        {
          id: 'p1-q8',
          number: 8,
          type: 'multiple-choice',
          instructionEs: '¿Qué función cumple la palabra destacada?',
          instructionHy: 'Ի՞նչ դեր է կատարում ընդգծված բառը։',
          sentenceEs: 'estos en «estos libros»',
          sentenceHy: 'estos-ը «այս գրքերը» արտահայտության մեջ',
          options: [
            { key: 'a', labelEs: 'determinante', labelHy: 'որոշիչ' },
            { key: 'b', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'c', labelEs: 'sustantivo', labelHy: 'գոյական' },
            { key: 'd', labelEs: 'nexo', labelHy: 'կապակցիչ' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) determinante',
          correctAnswerHy: 'որոշիչ (ցուցական)',
          explanationEs: '«Estos» acompaña directamente al sustantivo «libros», por lo que es un determinante demostrativo.',
          explanationHy: '«Estos»-ն անմիջապես ուղեկցում է «libros» գոյականին, ուստի ցուցական որոշիչ է։',
        },
      ],
    },
    {
      id: 'p1-s2',
      sectionNumber: 2,
      titleEs: '2. Busca la palabra indicada',
      titleHy: '2. Գտի՛ր նշված բառը',
      descriptionEs: 'Identifica la palabra concreta de la categoría pedida en cada oración.',
      descriptionHy: 'Գտի՛ր պահանջված քերականական կարգի կոնկրետ բառը յուրաքանչյուր նախադասության մեջ։',
      questions: [
        {
          id: 'p1-q9',
          number: 9,
          type: 'find-word',
          instructionEs: 'Busca el sustantivo en la siguiente oración:',
          instructionHy: 'Գտի՛ր գոյականը հետևյալ նախադասության մեջ՝',
          sentenceEs: 'El alumno estudia mucho.',
          sentenceHy: 'Աշակերտը շատ է սովորում։',
          targetPromptEs: 'Busca el sustantivo',
          targetPromptHy: 'Գտի՛ր գոյականը',
          correctAnswerText: 'alumno',
          correctAnswerHy: 'alumno (աշակերտ)',
          acceptableAnswers: ['alumno', 'el alumno'],
          explanationEs: '«Alumno» nombra a una persona, por lo que es el sustantivo.',
          explanationHy: '«Alumno»-ն անվանում է անձի (աշակերտ), ուստի գոյական է։',
        },
        {
          id: 'p1-q10',
          number: 10,
          type: 'find-word',
          instructionEs: 'Busca el adjetivo en la siguiente oración:',
          instructionHy: 'Գտի՛ր ածականը հետևյալ նախադասության մեջ՝',
          sentenceEs: 'La casa grande está cerca.',
          sentenceHy: 'Մեծ տունը մոտ է։',
          targetPromptEs: 'Busca el adjetivo',
          targetPromptHy: 'Գտի՛ր ածականը',
          correctAnswerText: 'grande',
          correctAnswerHy: 'grande (մեծ)',
          acceptableAnswers: ['grande'],
          explanationEs: '«Grande» describe la cualidad de la casa.',
          explanationHy: '«Grande»-ն նկարագրում է տան չափսը/հատկանիշը (մեծ)։',
        },
        {
          id: 'p1-q11',
          number: 11,
          type: 'find-word',
          instructionEs: 'Busca el verbo en la siguiente oración:',
          instructionHy: 'Գտի՛ր բայը հետևյալ նախադասության մեջ՝',
          sentenceEs: 'María corre rápidamente.',
          sentenceHy: 'Մարիան արագ է վազում։',
          targetPromptEs: 'Busca el verbo',
          targetPromptHy: 'Գտի՛ր բայը',
          correctAnswerText: 'corre',
          correctAnswerHy: 'corre (վազում է)',
          acceptableAnswers: ['corre'],
          explanationEs: '«Corre» es la acción que realiza María (del verbo correr).',
          explanationHy: '«Corre»-ն արտահայտում է գործողությունը (վազում է)։',
        },
        {
          id: 'p1-q12',
          number: 12,
          type: 'find-word',
          instructionEs: 'En la misma oración, busca el adverbio:',
          instructionHy: 'Նույն նախադասության մեջ գտի՛ր մակբայը՝',
          sentenceEs: 'María corre rápidamente.',
          sentenceHy: 'Մարիան արագ է վազում։',
          targetPromptEs: 'En la misma oración, busca el adverbio',
          targetPromptHy: 'Նույն նախադասության մեջ գտի՛ր մակբայը',
          correctAnswerText: 'rápidamente',
          correctAnswerHy: 'rápidamente (արագորեն)',
          acceptableAnswers: ['rápidamente', 'rapidamente'],
          explanationEs: '«Rápidamente» es un adverbio de modo que explica cómo corre María.',
          explanationHy: '«Rápidamente»-ն ձևի մակբայ է, ցույց է տալիս, թե ինչպես է վազում (արագորեն)։',
        },
        {
          id: 'p1-q13',
          number: 13,
          type: 'find-word',
          instructionEs: 'Busca el nexo en la siguiente oración:',
          instructionHy: 'Գտի՛ր կապակցիչը հետևյալ նախադասության մեջ՝',
          sentenceEs: 'Quiero ir, pero estoy cansado.',
          sentenceHy: 'Ուզում եմ գնալ, բայց հոգնած եմ։',
          targetPromptEs: 'Busca el nexo',
          targetPromptHy: 'Գտի՛ր կապակցիչը',
          correctAnswerText: 'pero',
          correctAnswerHy: 'pero (բայց)',
          acceptableAnswers: ['pero'],
          explanationEs: '«Pero» une las dos proposiciones de la oración coordinada.',
          explanationHy: '«Pero»-ն միացնում է նախադասության երկու մասերը (բայց)։',
        },
        {
          id: 'p1-q14',
          number: 14,
          type: 'find-word',
          instructionEs: 'Busca el pronombre en la siguiente oración:',
          instructionHy: 'Գտի՛ր դերանունը հետևյալ նախադասության մեջ՝',
          sentenceEs: 'Ella vive en Madrid.',
          sentenceHy: 'Նա ապրում է Մադրիդում։',
          targetPromptEs: 'Busca el pronombre',
          targetPromptHy: 'Գտի՛ր դերանունը',
          correctAnswerText: 'Ella',
          correctAnswerHy: 'Ella (նա)',
          acceptableAnswers: ['Ella', 'ella'],
          explanationEs: '«Ella» es un pronombre personal que sustituye al sujeto.',
          explanationHy: '«Ella»-ն անձնական դերանուն է (նա)։',
        },
        {
          id: 'p1-q15',
          number: 15,
          type: 'find-word',
          instructionEs: 'Busca el determinante en la siguiente oración:',
          instructionHy: 'Գտի՛ր որոշիչը հետևյալ նախադասության մեջ՝',
          sentenceEs: 'Mi hermano juega al fútbol.',
          sentenceHy: 'Իմ եղբայրը ֆուտբոլ է խաղում։',
          targetPromptEs: 'Busca el determinante',
          targetPromptHy: 'Գտի՛ր որոշիչը',
          correctAnswerText: 'Mi',
          correctAnswerHy: 'Mi (իմ)',
          acceptableAnswers: ['Mi', 'mi'],
          explanationEs: '«Mi» es un determinante posesivo que acompaña al sustantivo hermano.',
          explanationHy: '«Mi»-ն ստացական որոշիչ է, որն ուղեկցում է hermano գոյականին։',
        },
      ],
    },
    {
      id: 'p1-s3',
      sectionNumber: 3,
      titleEs: '3. Analiza toda la oración',
      titleHy: '3. Վերլուծի՛ր ամբողջ նախադասությունը',
      descriptionEs: 'Clasifica palabra por palabra cada elemento de la oración en su categoría correspondiente.',
      descriptionHy: 'Դասակարգի՛ր նախադասության յուրաքանչյուր բառը համապատասխան քերականական կարգի մեջ։',
      questions: [
        {
          id: 'p1-q16',
          number: 16,
          type: 'word-by-word',
          instructionEs: 'Clasifica cada palabra de la oración:',
          instructionHy: 'Դասակարգի՛ր նախադասության յուրաքանչյուր բառը՝',
          sentenceEs: 'Mi hermano pequeño juega muy bien.',
          sentenceHy: 'Իմ փոքր եղբայրը շատ լավ է խաղում։',
          correctAnswerText: 'Mi → determinante, hermano → sustantivo, pequeño → adjetivo, juega → verbo, muy → adverbio, bien → adverbio',
          breakdown: [
            { word: 'Mi', category: 'determinante', categoryHy: 'որոշիչ' },
            { word: 'hermano', category: 'sustantivo', categoryHy: 'գոյական' },
            { word: 'pequeño', category: 'adjetivo', categoryHy: 'ածական' },
            { word: 'juega', category: 'verbo', categoryHy: 'բայ' },
            { word: 'muy', category: 'adverbio', categoryHy: 'մակբայ' },
            { word: 'bien', category: 'adverbio', categoryHy: 'մակբայ' },
          ],
          explanationEs: '«Mi» acompaña a hermano (determinante); «hermano» nombra (sustantivo); «pequeño» cualifica (adjetivo); «juega» acción (verbo); «muy» intensifica (adverbio); «bien» describe el modo (adverbio).',
          explanationHy: '«Mi» որոշիչ է, «hermano» գոյական է, «pequeño» ածական է, «juega» բայ է, «muy» և «bien» մակբայներ են։',
        },
        {
          id: 'p1-q17',
          number: 17,
          type: 'word-by-word',
          instructionEs: 'Clasifica cada palabra de la oración:',
          instructionHy: 'Դասակարգի՛ր նախադասության յուրաքանչյուր բառը՝',
          sentenceEs: 'Ella estudia mucho porque tiene examen.',
          sentenceHy: 'Նա շատ է սովորում, որովհետև քննություն ունի։',
          correctAnswerText: 'Ella → pronombre, estudia → verbo, mucho → adverbio, porque → nexo, tiene → verbo, examen → sustantivo',
          breakdown: [
            { word: 'Ella', category: 'pronombre', categoryHy: 'դերանուն' },
            { word: 'estudia', category: 'verbo', categoryHy: 'բայ' },
            { word: 'mucho', category: 'adverbio', categoryHy: 'մակբայ' },
            { word: 'porque', category: 'nexo', categoryHy: 'կապակցիչ' },
            { word: 'tiene', category: 'verbo', categoryHy: 'բայ' },
            { word: 'examen', category: 'sustantivo', categoryHy: 'գոյական' },
          ],
          explanationEs: '«Ella» pronombre personal; «estudia» verbo; «mucho» adverbio de cantidad; «porque» nexo causal; «tiene» verbo tener; «examen» sustantivo.',
          explanationHy: '«Ella» դերանուն է, «estudia» բայ է, «mucho» մակբայ է, «porque» կապակցիչ է, «tiene» բայ է, «examen» գոյական է։',
        },
        {
          id: 'p1-q18',
          number: 18,
          type: 'word-by-word',
          instructionEs: 'Clasifica cada palabra de la oración:',
          instructionHy: 'Դասակարգի՛ր նախադասության յուրաքանչյուր բառը՝',
          sentenceEs: 'Estos alumnos nuevos trabajan bastante.',
          sentenceHy: 'Այս նոր աշակերտները բավական շատ են աշխատում։',
          correctAnswerText: 'Estos → determinante, alumnos → sustantivo, nuevos → adjetivo, trabajan → verbo, bastante → adverbio',
          breakdown: [
            { word: 'Estos', category: 'determinante', categoryHy: 'որոշիչ' },
            { word: 'alumnos', category: 'sustantivo', categoryHy: 'գոյական' },
            { word: 'nuevos', category: 'adjetivo', categoryHy: 'ածական' },
            { word: 'trabajan', category: 'verbo', categoryHy: 'բայ' },
            { word: 'bastante', category: 'adverbio', categoryHy: 'մակբայ' },
          ],
          explanationEs: '«Estos» determinante demostrativo; «alumnos» sustantivo plural; «nuevos» adjetivo; «trabajan» verbo; «bastante» adverbio de cantidad.',
          explanationHy: '«Estos» որոշիչ է, «alumnos» գոյական է, «nuevos» ածական է, «trabajan» բայ է, «bastante» մակբայ է։',
        },
      ],
    },
    {
      id: 'p1-s4',
      sectionNumber: 4,
      titleEs: '4. Encuentra el intruso',
      titleHy: '4. Գտի՛ր ավելորդ բառը',
      descriptionEs: 'Tres palabras pertenecen a la misma categoría gramatical y una no. ¡Encuentra el intruso!',
      descriptionHy: 'Երեք բառ պատկանում են միևնույն քերականական կարգին, իսկ մեկը՝ ոչ։ Գտի՛ր ավելորդը։',
      questions: [
        {
          id: 'p1-q19',
          number: 19,
          type: 'odd-one-out',
          instructionEs: 'Tres son sustantivos y uno no:',
          instructionHy: 'Երեքը գոյական են, իսկ մեկը՝ ոչ․',
          options: [
            { key: 'a', labelEs: 'mesa', labelHy: 'սեղան (գոյական)' },
            { key: 'b', labelEs: 'colegio', labelHy: 'դպրոց (գոյական)' },
            { key: 'c', labelEs: 'estudiar', labelHy: 'սովորել (բայ)' },
            { key: 'd', labelEs: 'alumno', labelHy: 'աշակերտ (գոյական)' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) estudiar',
          correctAnswerHy: 'c) estudiar (բայ է, ոչ թե գոյական)',
          explanationEs: '«Mesa», «colegio» y «alumno» son sustantivos; «estudiar» es un verbo en infinitivo.',
          explanationHy: '«estudiar»-ը բայ է անորոշ ձևով (սովորել), իսկ մնացածը գոյականներ են։',
        },
        {
          id: 'p1-q20',
          number: 20,
          type: 'odd-one-out',
          instructionEs: 'Tres son adjetivos y uno no:',
          instructionHy: 'Երեքը ածական են, իսկ մեկը՝ ոչ․',
          options: [
            { key: 'a', labelEs: 'bonito', labelHy: 'գեղեցիկ (ածական)' },
            { key: 'b', labelEs: 'difícil', labelHy: 'դժվար (ածական)' },
            { key: 'c', labelEs: 'rápido', labelHy: 'արագ (ածական)' },
            { key: 'd', labelEs: 'correr', labelHy: 'վազել (բայ)' },
          ],
          correctOptionKey: 'd',
          correctAnswerText: 'd) correr',
          correctAnswerHy: 'd) correr (բայ է, ոչ թե ածական)',
          explanationEs: '«Bonito», «difícil» y «rápido» expresan cualidades (adjetivos); «correr» es un verbo.',
          explanationHy: '«correr»-ը բայ է (վազել), մյուս երեքը ածականներ են։',
        },
        {
          id: 'p1-q21',
          number: 21,
          type: 'odd-one-out',
          instructionEs: 'Tres son verbos y uno no:',
          instructionHy: 'Երեքը բայ են, իսկ մեկը՝ ոչ․',
          options: [
            { key: 'a', labelEs: 'estudiar', labelHy: 'սովորել (բայ)' },
            { key: 'b', labelEs: 'pensar', labelHy: 'մտածել (բայ)' },
            { key: 'c', labelEs: 'casa', labelHy: 'տուն (գոյական)' },
            { key: 'd', labelEs: 'escribir', labelHy: 'գրել (բայ)' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) casa',
          correctAnswerHy: 'c) casa (գոյական է, ոչ թե բայ)',
          explanationEs: '«Estudiar», «pensar» y «escribir» son verbos; «casa» es un sustantivo.',
          explanationHy: '«casa»-ն գոյական է (տուն), իսկ մյուսները բայեր են։',
        },
        {
          id: 'p1-q22',
          number: 22,
          type: 'odd-one-out',
          instructionEs: 'Tres son adverbios y uno no:',
          instructionHy: 'Երեքը մակբայ են, իսկ մեկը՝ ոչ․',
          options: [
            { key: 'a', labelEs: 'hoy', labelHy: 'այսօր (մակբայ)' },
            { key: 'b', labelEs: 'aquí', labelHy: 'այստեղ (մակբայ)' },
            { key: 'c', labelEs: 'lentamente', labelHy: 'դանդաղ (մակբայ)' },
            { key: 'd', labelEs: 'alumno', labelHy: 'աշակերտ (գոյական)' },
          ],
          correctOptionKey: 'd',
          correctAnswerText: 'd) alumno',
          correctAnswerHy: 'd) alumno (գոյական է, ոչ թե մակբայ)',
          explanationEs: '«Hoy», «aquí» y «lentamente» son adverbios; «alumno» es un sustantivo.',
          explanationHy: '«alumno»-ն գոյական է (աշակերտ), իսկ մյուսները մակբայներ են։',
        },
        {
          id: 'p1-q23',
          number: 23,
          type: 'odd-one-out',
          instructionEs: 'Tres son nexos y uno no:',
          instructionHy: 'Երեքը կապակցիչ են, իսկ մեկը՝ ոչ․',
          options: [
            { key: 'a', labelEs: 'y', labelHy: 'և (շաղկապ/կապակցիչ)' },
            { key: 'b', labelEs: 'pero', labelHy: 'բայց (կապակցիչ)' },
            { key: 'c', labelEs: 'porque', labelHy: 'որովհետև (կապակցիչ)' },
            { key: 'd', labelEs: 'ella', labelHy: 'նա (դերանուն)' },
          ],
          correctOptionKey: 'd',
          correctAnswerText: 'd) ella',
          correctAnswerHy: 'd) ella (դերանուն է, ոչ թե կապակցիչ)',
          explanationEs: '«Y», «pero» y «porque» son conjunciones / nexos; «ella» es un pronombre personal.',
          explanationHy: '«ella»-ն դերանուն է, մյուս երեքը կապակցիչներ (շաղկապներ) են։',
        },
        {
          id: 'p1-q24',
          number: 24,
          type: 'odd-one-out',
          instructionEs: 'Tres son pronombres y uno no:',
          instructionHy: 'Երեքը դերանուն են, իսկ մեկը՝ ոչ․',
          options: [
            { key: 'a', labelEs: 'yo', labelHy: 'ես (դերանուն)' },
            { key: 'b', labelEs: 'tú', labelHy: 'դու (դերանուն)' },
            { key: 'c', labelEs: 'nosotros', labelHy: 'մենք (դերանուն)' },
            { key: 'd', labelEs: 'mi', labelHy: 'իմ (որոշիչ/ստացական)' },
          ],
          correctOptionKey: 'd',
          correctAnswerText: 'd) mi',
          correctAnswerHy: 'd) mi (որոշիչ է, որովհետև գալիս է գոյականի հետ)',
          explanationEs: '«Yo», «tú» y «nosotros» son pronombres personales tónicos; «mi» sin tilde es determinante posesivo (ej. mi casa).',
          explanationHy: '«mi»-ն առանց շեշտի ստացական որոշիչ է (օր.՝ mi casa), իսկ մյուսները անձնական դերանուններ են։',
        },
        {
          id: 'p1-q25',
          number: 25,
          type: 'odd-one-out',
          instructionEs: 'Tres pueden ser determinantes y uno no:',
          instructionHy: 'Երեքը կարող են լինել որոշիչ, իսկ մեկը՝ ոչ․',
          options: [
            { key: 'a', labelEs: 'el', labelHy: 'որոշիչ հոդ' },
            { key: 'b', labelEs: 'mi', labelHy: 'ստացական որոշիչ' },
            { key: 'c', labelEs: 'este', labelHy: 'ցուցական որոշիչ' },
            { key: 'd', labelEs: 'rápidamente', labelHy: 'մակբայ' },
          ],
          correctOptionKey: 'd',
          correctAnswerText: 'd) rápidamente',
          correctAnswerHy: 'd) rápidamente (մակբայ է)',
          explanationEs: '«El» (artículo), «mi» (posesivo) y «este» (demostrativo) son determinantes; «rápidamente» es un adverbio.',
          explanationHy: '«rápidamente»-ն մակբայ է (արագորեն), իսկ մյուս երեքը որոշիչներ են։',
        },
      ],
    },
    {
      id: 'p1-s5',
      sectionNumber: 5,
      titleEs: '5. Sustituye por un pronombre',
      titleHy: '5. Փոխարինի՛ր դերանունով',
      descriptionEs: 'Sustituye el sujeto o sintagma nominal por el pronombre personal correspondiente.',
      descriptionHy: 'Գոյականական անդամը կամ ենթական փոխարինի՛ր համապատասխան անձնական դերանունով։',
      questions: [
        {
          id: 'p1-q26',
          number: 26,
          type: 'replace-pronoun',
          instructionEs: 'Sustituye «María» por un pronombre personal:',
          instructionHy: 'María-ն փոխարինի՛ր անձնական դերանունով՝',
          sentenceEs: 'María estudia mucho.',
          sentenceHy: 'Մարիան շատ է սովորում։',
          targetPromptEs: '→ __________ estudia mucho.',
          targetPromptHy: '→ __________ estudia mucho.',
          correctAnswerText: 'Ella',
          correctAnswerHy: 'Ella (նա - իգական)',
          acceptableAnswers: ['Ella', 'ella', 'Ella estudia mucho.'],
          explanationEs: 'María es tercera persona singular femenina → «Ella».',
          explanationHy: 'Մարիան եզակի թվի 3-րդ դեմք իգական է → «Ella» (նա)։',
        },
        {
          id: 'p1-q27',
          number: 27,
          type: 'replace-pronoun',
          instructionEs: 'Sustituye «Pedro y Carlos» por un pronombre:',
          instructionHy: '«Pedro y Carlos»-ը փոխարինի՛ր դերանունով՝',
          sentenceEs: 'Pedro y Carlos juegan al fútbol.',
          sentenceHy: 'Պեդրոն և Կառլոսը ֆուտբոլ են խաղում։',
          targetPromptEs: '→ __________ juegan al fútbol.',
          targetPromptHy: '→ __________ juegan al fútbol.',
          correctAnswerText: 'Ellos',
          correctAnswerHy: 'Ellos (նրանք)',
          acceptableAnswers: ['Ellos', 'ellos', 'Ellos juegan al fútbol.'],
          explanationEs: 'Pedro y Carlos son tercera persona plural masculina → «Ellos».',
          explanationHy: 'Երկու տղա (հոգնակի 3-րդ դեմք) → «Ellos» (նրանք)։',
        },
        {
          id: 'p1-q28',
          number: 28,
          type: 'replace-pronoun',
          instructionEs: 'Sustituye «Ana y yo» por un pronombre:',
          instructionHy: '«Ana y yo»-ն փոխարինի՛ր դերանունով՝',
          sentenceEs: 'Ana y yo vamos al colegio.',
          sentenceHy: 'Անան և ես գնում ենք դպրոց։',
          targetPromptEs: '→ __________ vamos al colegio.',
          targetPromptHy: '→ __________ vamos al colegio.',
          correctAnswerText: 'Nosotros',
          correctAnswerHy: 'Nosotros (մենք)',
          acceptableAnswers: ['Nosotros', 'nosotros', 'Nosotras', 'nosotras', 'Nosotros vamos al colegio.'],
          explanationEs: 'Ana y yo incluye al hablante (primera persona del plural) → «Nosotros» (o nosotras).',
          explanationHy: 'Անան և ես ներառում է խոսողին (1-ին դեմք հոգնակի) → «Nosotros» (մենք)։',
        },
      ],
    },
    {
      id: 'p1-s6',
      sectionNumber: 6,
      titleEs: '6. Determinante o pronombre',
      titleHy: '6. Որոշի՞չ, թե՞ դերանուն',
      descriptionEs: '¡Cuidado con esta distinción típica de examen! El determinante acompaña; el pronombre sustituye.',
      descriptionHy: 'Ուշադի՛ր եղիր այս կարևոր տարբերությանը։ Որոշիչն ուղեկցում է, իսկ դերանունը՝ փոխարինում։',
      questions: [
        {
          id: 'p1-q29',
          number: 29,
          type: 'det-or-pron',
          instructionEs: 'En esta frase, ¿qué es la palabra «Este»?',
          instructionHy: 'Այս նախադասության մեջ ի՞նչ է «Este» բառը՝',
          sentenceEs: 'Este libro es interesante.',
          sentenceHy: 'Այս գիրքը հետաքրքիր է։',
          options: [
            { key: 'a', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'b', labelEs: 'determinante', labelHy: 'որոշիչ' },
          ],
          correctOptionKey: 'b',
          correctAnswerText: 'b) determinante',
          correctAnswerHy: 'b) determinante (որոշիչ)',
          explanationEs: '«Este» acompaña al sustantivo «libro», por tanto es determinante.',
          explanationHy: '«Este»-ն ուղեկցում է «libro» գոյականին, ուստի որոշիչ է։',
        },
        {
          id: 'p1-q30',
          number: 30,
          type: 'det-or-pron',
          instructionEs: 'En esta frase, ¿qué es la palabra «Este»?',
          instructionHy: 'Այս նախադասության մեջ ի՞նչ է «Este» բառը՝',
          sentenceEs: 'Este es interesante.',
          sentenceHy: 'Սա հետաքրքիր է։',
          options: [
            { key: 'a', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'b', labelEs: 'determinante', labelHy: 'որոշիչ' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) pronombre',
          correctAnswerHy: 'a) pronombre (դերանուն)',
          explanationEs: '«Este» aparece solo y sustituye al sustantivo, por tanto es pronombre.',
          explanationHy: '«Este»-ն հանդես է գալիս միայնակ և փոխարինում է գոյականին, ուստի դերանուն է։',
        },
        {
          id: 'p1-q31',
          number: 31,
          type: 'det-or-pron',
          instructionEs: 'En esta frase, ¿qué es la palabra «Mi»?',
          instructionHy: 'Այս նախադասության մեջ ի՞նչ է «Mi» բառը՝',
          sentenceEs: 'Mi mochila está aquí.',
          sentenceHy: 'Իմ պայուսակն այստեղ է։',
          options: [
            { key: 'a', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'b', labelEs: 'determinante', labelHy: 'որոշիչ' },
          ],
          correctOptionKey: 'b',
          correctAnswerText: 'b) determinante',
          correctAnswerHy: 'b) determinante (որոշիչ)',
          explanationEs: '«Mi» acompaña al sustantivo «mochila», por tanto es determinante posesivo.',
          explanationHy: '«Mi»-ն ուղեկցում է «mochila» գոյականին, ուստի ստացական որոշիչ է։',
        },
        {
          id: 'p1-q32',
          number: 32,
          type: 'det-or-pron',
          instructionEs: 'En esta frase, ¿qué es la palabra «Ella»?',
          instructionHy: 'Այս նախադասության մեջ ի՞նչ է «Ella» բառը՝',
          sentenceEs: 'Ella tiene dos hermanos.',
          sentenceHy: 'Նա երկու եղբայր ունի։',
          options: [
            { key: 'a', labelEs: 'pronombre', labelHy: 'դերանուն' },
            { key: 'b', labelEs: 'determinante', labelHy: 'որոշիչ' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) pronombre',
          correctAnswerHy: 'a) pronombre (դերանուն)',
          explanationEs: '«Ella» funciona como sujeto y sustituye a una persona, por tanto es pronombre.',
          explanationHy: '«Ella»-ն հանդես է գալիս որպես ենթակա և փոխարինում է անձի, ուստի դերանուն է։',
        },
      ],
    },
    {
      id: 'p1-s7',
      sectionNumber: 7,
      titleEs: '7. Completa con la categoría correcta',
      titleHy: '7. Լրացրո՛ւ ճիշտ քերականական կարգով',
      descriptionEs: 'Usa una de las 7 categorías: sustantivo, adjetivo, verbo, adverbio, nexo, pronombre o determinante.',
      descriptionHy: 'Օգտագործի՛ր 7 կարգերից մեկը՝ sustantivo, adjetivo, verbo, adverbio, nexo, pronombre, determinante:',
      questions: [
        {
          id: 'p1-q33',
          number: 33,
          type: 'fill-category',
          instructionEs: 'Indica la categoría de «Casa»:',
          instructionHy: 'Նշի՛ր «Casa» բառի քերականական կարգը՝',
          sentenceEs: '«Casa» es un __________.',
          sentenceHy: '«Casa» (տուն) բառը __________ է։',
          correctAnswerText: 'sustantivo',
          correctAnswerHy: 'sustantivo (գոյական)',
          acceptableAnswers: ['sustantivo', 'un sustantivo'],
          explanationEs: '«Casa» nombra un objeto/lugar, por lo que es un sustantivo.',
          explanationHy: '«Casa»-ն տեղ/առարկա է անվանում, ուստի գոյական է։',
        },
        {
          id: 'p1-q34',
          number: 34,
          type: 'fill-category',
          instructionEs: 'Indica la categoría de «Bonito» en «un paisaje bonito»:',
          instructionHy: 'Նշի՛ր «Bonito» բառի կարգը «un paisaje bonito» արտահայտության մեջ՝',
          sentenceEs: '«Bonito» en «un paisaje bonito» es un __________.',
          sentenceHy: '«Bonito»-ն «գեղեցիկ բնապատկեր» արտահայտության մեջ __________ է։',
          correctAnswerText: 'adjetivo',
          correctAnswerHy: 'adjetivo (ածական)',
          acceptableAnswers: ['adjetivo', 'un adjetivo'],
          explanationEs: '«Bonito» describe una cualidad del sustantivo paisaje.',
          explanationHy: '«Bonito»-ն նկարագրում է բնապատկերի հատկանիշը (ածական)։',
        },
        {
          id: 'p1-q35',
          number: 35,
          type: 'fill-category',
          instructionEs: 'Indica la categoría de «Correr»:',
          instructionHy: 'Նշի՛ր «Correr» բառի քերականական կարգը՝',
          sentenceEs: '«Correr» es un __________.',
          sentenceHy: '«Correr» (վազել) բառը __________ է։',
          correctAnswerText: 'verbo',
          correctAnswerHy: 'verbo (բայ)',
          acceptableAnswers: ['verbo', 'un verbo'],
          explanationEs: '«Correr» expresa una acción en infinitivo.',
          explanationHy: '«Correr»-ն արտահայտում է գործողություն (բայ)։',
        },
        {
          id: 'p1-q36',
          number: 36,
          type: 'fill-category',
          instructionEs: 'Indica la categoría de «Hoy»:',
          instructionHy: 'Նշի՛ր «Hoy» բառի քերականական կարգը՝',
          sentenceEs: '«Hoy» es un __________.',
          sentenceHy: '«Hoy» (այսօր) բառը __________ է։',
          correctAnswerText: 'adverbio',
          correctAnswerHy: 'adverbio (մակբայ)',
          acceptableAnswers: ['adverbio', 'un adverbio'],
          explanationEs: '«Hoy» indica tiempo cronológico.',
          explanationHy: '«Hoy»-ը ցույց է տալիս ժամանակ (մակբայ)։',
        },
        {
          id: 'p1-q37',
          number: 37,
          type: 'fill-category',
          instructionEs: 'Indica la categoría de «Porque»:',
          instructionHy: 'Նշի՛ր «Porque» բառի քերականական կարգը՝',
          sentenceEs: '«Porque» es un __________.',
          sentenceHy: '«Porque» (որովհետև) բառը __________ է։',
          correctAnswerText: 'nexo',
          correctAnswerHy: 'nexo (կապակցիչ / շաղկապ)',
          acceptableAnswers: ['nexo', 'un nexo', 'conjunción', 'conjuncion'],
          explanationEs: '«Porque» une dos proposiciones subordinando una causa.',
          explanationHy: '«Porque»-ն միացնում է երկու նախադասություն (կապակցիչ)։',
        },
        {
          id: 'p1-q38',
          number: 38,
          type: 'fill-category',
          instructionEs: 'Indica la categoría de «Nosotros»:',
          instructionHy: 'Նշի՛ր «Nosotros» բառի քերականական կարգը՝',
          sentenceEs: '«Nosotros» es un __________.',
          sentenceHy: '«Nosotros» (մենք) բառը __________ է։',
          correctAnswerText: 'pronombre',
          correctAnswerHy: 'pronombre (դերանուն)',
          acceptableAnswers: ['pronombre', 'un pronombre'],
          explanationEs: '«Nosotros» sustituye a la 1ª persona plural.',
          explanationHy: '«Nosotros»-ը փոխարինում է 1-ին դեմք հոգնակի թվին (դերանուն)։',
        },
        {
          id: 'p1-q39',
          number: 39,
          type: 'fill-category',
          instructionEs: 'Indica la categoría de «La» en «la profesora»:',
          instructionHy: 'Նշի՛ր «La» բառի կարգը «la profesora» արտահայտության մեջ՝',
          sentenceEs: '«La» en «la profesora» es un __________.',
          sentenceHy: '«La»-ն «ուսուցչուհին» արտահայտության մեջ __________ է։',
          correctAnswerText: 'determinante',
          correctAnswerHy: 'determinante (որոշիչ - որոշյալ հոդ)',
          acceptableAnswers: ['determinante', 'un determinante', 'artículo', 'articulo'],
          explanationEs: '«La» es un artículo determinado que acompaña al sustantivo profesora.',
          explanationHy: '«La»-ն որոշյալ հոդ (որոշիչ) է, որն ուղեկցում է profesora գոյականին։',
        },
      ],
    },
    {
      id: 'p1-s8',
      sectionNumber: 8,
      titleEs: '8. Texto tipo examen',
      titleHy: '8. Տեքստ՝ քննության նման',
      descriptionEs: 'Lee atentamente el texto y responde a las preguntas 40 a 46.',
      descriptionHy: 'Ուշադիր կարդա՛ տեքստը և պատասխանի՛ր 40-ից 46 հարցերին։',
      contextEs: 'Mi amigo Carlos vive en una ciudad pequeña, pero estudia en un colegio grande. Él normalmente llega temprano porque su casa está bastante cerca. Sus profesores son amables y Carlos trabaja mucho.',
      contextHy: 'Իմ ընկեր Կառլոսն ապրում է մի փոքր քաղաքում, բայց սովորում է մեծ դպրոցում։ Նա սովորաբար շուտ է հասնում, որովհետև նրա տունը բավական մոտ է։ Նրա ուսուցիչները բարեհամբույր են, և Կառլոսը շատ է աշխատում։',
      questions: [
        {
          id: 'p1-q40',
          number: 40,
          type: 'text-analysis',
          instructionEs: 'Busca dos sustantivos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երկու գոյական՝',
          sentenceEs: 'Busca dos sustantivos.',
          sentenceHy: 'Գտի՛ր երկու գոյական։',
          correctAnswerText: 'amigo, Carlos, ciudad, colegio, casa, profesores',
          correctAnswerHy: 'amigo, Carlos, ciudad, colegio, casa, profesores',
          explanationEs: 'Cualquiera de estos es correcto: amigo, Carlos, ciudad, colegio, casa, profesores.',
          explanationHy: 'Ցանկացած երկուսը ճիշտ են՝ amigo (ընկեր), Carlos, ciudad (քաղաք), colegio (դպրոց), casa (տուն), profesores (ուսուցիչներ)։',
        },
        {
          id: 'p1-q41',
          number: 41,
          type: 'text-analysis',
          instructionEs: 'Busca dos adjetivos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երկու ածական՝',
          sentenceEs: 'Busca dos adjetivos.',
          sentenceHy: 'Գտի՛ր երկու ածական։',
          correctAnswerText: 'pequeña, grande, amables',
          correctAnswerHy: 'pequeña (փոքր), grande (մեծ), amables (բարեհամբույր)',
          explanationEs: 'En el texto aparecen: pequeña (modifica ciudad), grande (modifica colegio), amables (describe profesores).',
          explanationHy: 'Տեքստում կան՝ pequeña (փոքր), grande (մեծ), amables (բարեհամբույր)։',
        },
        {
          id: 'p1-q42',
          number: 42,
          type: 'text-analysis',
          instructionEs: 'Busca dos verbos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երկու բայ՝',
          sentenceEs: 'Busca dos verbos.',
          sentenceHy: 'Գտի՛ր երկու բայ։',
          correctAnswerText: 'vive, estudia, llega, está, son, trabaja',
          correctAnswerHy: 'vive, estudia, llega, está, son, trabaja',
          explanationEs: 'Verbos presentes en el texto: vive, estudia, llega, está, son, trabaja.',
          explanationHy: 'Տեքստի բայերն են՝ vive (ապրում է), estudia (սովորում է), llega (հասնում է), está (գտնվում է), son (են), trabaja (աշխատում է)։',
        },
        {
          id: 'p1-q43',
          number: 43,
          type: 'text-analysis',
          instructionEs: 'Busca dos adverbios en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երկու մակբայ՝',
          sentenceEs: 'Busca dos adverbios.',
          sentenceHy: 'Գտի՛ր երկու մակբայ։',
          correctAnswerText: 'normalmente, temprano, bastante, cerca, mucho',
          correctAnswerHy: 'normalmente, temprano, bastante, cerca, mucho',
          explanationEs: 'Adverbios presentes: normalmente (modo), temprano (tiempo), bastante (cantidad), cerca (lugar), mucho (cantidad).',
          explanationHy: 'Մակբայներ՝ normalmente (սովորաբար), temprano (շուտ), bastante (բավական), cerca (մոտ), mucho (շատ)։',
        },
        {
          id: 'p1-q44',
          number: 44,
          type: 'text-analysis',
          instructionEs: 'Busca dos nexos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երկու կապակցիչ՝',
          sentenceEs: 'Busca dos nexos.',
          sentenceHy: 'Գտի՛ր երկու կապակցիչ։',
          correctAnswerText: 'pero, porque, y',
          correctAnswerHy: 'pero (բայց), porque (որովհետև), y (և)',
          explanationEs: 'Nexos o conjunciones que unen oraciones en el texto: pero, porque, y.',
          explanationHy: 'Կապակցիչներ (շաղկապներ) տեքստում՝ pero (բայց), porque (որովհետև), y (և)։',
        },
        {
          id: 'p1-q45',
          number: 45,
          type: 'text-analysis',
          instructionEs: 'Busca un pronombre en el texto:',
          instructionHy: 'Տեքստից գտի՛ր մեկ դերանուն՝',
          sentenceEs: 'Busca un pronombre.',
          sentenceHy: 'Գտի՛ր մեկ դերանուն։',
          correctAnswerText: 'Él',
          correctAnswerHy: 'Él (նա)',
          acceptableAnswers: ['Él', 'él'],
          explanationEs: '«Él» (con tilde) es el pronombre personal que sustituye a Carlos.',
          explanationHy: '«Él»-ը (շեշտով) անձնական դերանուն է, որը փոխարինում է Կառլոսին։',
        },
        {
          id: 'p1-q46',
          number: 46,
          type: 'text-analysis',
          instructionEs: 'Busca dos determinantes en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երկու որոշիչ՝',
          sentenceEs: 'Busca dos determinantes.',
          sentenceHy: 'Գտի՛ր երկու որոշիչ։',
          correctAnswerText: 'mi, una, un, su, sus',
          correctAnswerHy: 'mi (իմ), una (մի), un (մի), su (նրա), sus (նրա/նրանց)',
          explanationEs: 'Determinantes que acompañan a sustantivos: mi (amigo), una (ciudad), un (colegio), su (casa), sus (profesores).',
          explanationHy: 'Որոշիչներ՝ mi (amigo), una (ciudad), un (colegio), su (casa), sus (profesores)։',
        },
      ],
    },
    {
      id: 'p1-s9',
      sectionNumber: 9,
      titleEs: '9. Preguntas de razonamiento',
      titleHy: '9. Մտածելու հարցեր',
      descriptionEs: 'Preguntas conceptuales para afianzar el criterio gramatical.',
      descriptionHy: 'Հայեցակարգային հարցեր՝ քերականական մտածողությունը հստակեցնելու համար։',
      questions: [
        {
          id: 'p1-q47',
          number: 47,
          type: 'reasoning',
          instructionEs: '¿Qué categoría es y por qué?',
          instructionHy: 'Ի՞նչ կարգ է և ինչո՞ւ՝',
          sentenceEs: 'En «un coche rápido», ¿qué categoría es rápido? ¿Por qué?',
          sentenceHy: '«Un coche rápido» արտահայտության մեջ ի՞նչ կարգ է rápido-ն։ Ինչո՞ւ։',
          correctAnswerText: 'rápido → adjetivo, porque describe al sustantivo coche.',
          correctAnswerHy: 'Ածական է, որովհետև նկարագրում է coche (մեքենա) գոյականը։',
          explanationEs: '«Rápido» concuerda con el sustantivo «coche» y expresa una de sus cualidades permanentes o transitorias.',
          explanationHy: '«Rápido»-ն համաձայնում է «coche» գոյականի հետ և նկարագրում նրա որակը, ուստի ածական է։',
        },
        {
          id: 'p1-q48',
          number: 48,
          type: 'multiple-choice',
          instructionEs: '¿Qué función tiene en este uso escolar?',
          instructionHy: 'Ի՞նչ դեր ունի դպրոցական այս գործածության մեջ՝',
          sentenceEs: 'En «Carlos corre rápido», ¿qué función tiene rápido?',
          sentenceHy: '«Carlos corre rápido» արտահայտության մեջ ի՞նչ դեր ունի rápido-ն։',
          options: [
            { key: 'a', labelEs: 'sustantivo', labelHy: 'գոյական' },
            { key: 'b', labelEs: 'adjetivo', labelHy: 'ածական' },
            { key: 'c', labelEs: 'adverbio', labelHy: 'մակբայ' },
            { key: 'd', labelEs: 'determinante', labelHy: 'որոշիչ' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) adverbio, porque modifica el verbo corre.',
          correctAnswerHy: 'c) մակբայ, որովհետև լրացնում է corre բայի իմաստը։',
          explanationEs: 'Aquí «rápido» equivale a «rápidamente», modificando al verbo «corre». Por tanto funciona como adverbio.',
          explanationHy: 'Այստեղ «rápido»-ն հավասարազոր է «rápidamente»-ին (արագորեն) և լրացնում է «corre» (վազում է) բային, ուստի մակբայ է։',
        },
        {
          id: 'p1-q49',
          number: 49,
          type: 'reasoning',
          instructionEs: 'Explica la diferencia fundamental:',
          instructionHy: 'Բացատրի՛ր հիմնական տարբերությունը՝',
          sentenceEs: '¿Qué diferencia hay entre pronombre y determinante?',
          sentenceHy: 'Ի՞նչ տարբերություն կա դերանվան և որոշիչի միջև։',
          correctAnswerText: 'El determinante acompaña a un sustantivo; el pronombre lo sustituye.',
          correctAnswerHy: 'Որոշիչը ուղեկցում է գոյականին, իսկ դերանունը փոխարինում է գոյականին։',
          explanationEs: 'Regla de oro: Determinante + Sustantivo (ej. «este libro»). Pronombre va solo (ej. «este es bueno»).',
          explanationHy: 'Ոսկե կանոն. Որոշիչ + Գոյական (օր.՝ «este libro» - այս գիրքը): Իսկ դերանունը հանդես է գալիս առանձին («este es bueno» - սա լավն է)։',
        },
        {
          id: 'p1-q50',
          number: 50,
          type: 'reasoning',
          instructionEs: '¿Qué categoría une dos ideas en la siguiente oración?',
          instructionHy: 'Ո՞ր քերականական կարգն է կապում երկու միտքը հետևյալ նախադասության մեջ՝',
          sentenceEs: '«Quiero salir, pero está lloviendo.»',
          sentenceHy: '«Ուզում եմ դուրս գալ, բայց անձրև է գալիս։»',
          correctAnswerText: 'pero → nexo.',
          correctAnswerHy: 'pero-ն կապակցիչ (nexo) է։',
          explanationEs: '«Pero» es un nexo coordinante adversativo que une las dos proposiciones.',
          explanationHy: '«pero»-ն հակադրական շաղկապ (կապակցիչ) է, որը կապում է երկու միտքը։',
        },
      ],
    },
  ],
};
