import { PartData } from './types';

export const PART_2_DATA: PartData = {
  id: 'part-2',
  partNumber: 2,
  titleEs: 'Categorías gramaticales — Práctica de examen (1º ESO)',
  titleHy: 'Քերականական կարգեր — Քննության վարժություններ (1º ESO)',
  subtitleEs: 'Ejercicios contextuales avanzados para analizar palabras en contexto real de examen.',
  subtitleHy: 'Խորացված համատեքստային վարժություններ՝ իրական քննական ձևաչափով բառերը վերլուծելու համար։',
  sections: [
    {
      id: 'p2-s1',
      sectionNumber: 1,
      titleEs: '1. Analiza las palabras destacadas',
      titleHy: '1. Վերլուծի՛ր ընդգծված բառերը',
      descriptionEs: 'Identifica la categoría gramatical de las palabras destacadas según su contexto en la frase.',
      descriptionHy: 'Որոշի՛ր առանձնացված բառերի քերականական կարգը՝ ըստ նախադասության մեջ դրանց համատեքստի։',
      questions: [
        {
          id: 'p2-q1',
          number: 1,
          type: 'multiple-choice',
          instructionEs: '¿Qué son «mi» y «dos» en esta frase?',
          instructionHy: 'Ի՞նչ են «mi» և «dos» բառերը այս նախադասության մեջ՝',
          sentenceEs: 'Mi hermana compra dos libros nuevos.',
          sentenceHy: 'Իմ քույրը գնում է երկու նոր գիրք։',
          options: [
            { key: 'a', labelEs: 'Pronombres', labelHy: 'Դերանուններ' },
            { key: 'b', labelEs: 'Determinantes', labelHy: 'Որոշիչներ' },
            { key: 'c', labelEs: 'Adverbios', labelHy: 'Մակբայներ' },
            { key: 'd', labelEs: 'Nexos', labelHy: 'Կապակցիչներ' },
          ],
          correctOptionKey: 'b',
          correctAnswerText: 'b) determinantes',
          correctAnswerHy: 'b) determinantes (որոշիչներ)',
          explanationEs: '«Mi» y «dos» acompañan y determinan a los sustantivos «hermana» y «libros».',
          explanationHy: '«Mi» և «dos» բառերը որոշիչներ են, որովհետև ուղեկցում են «hermana» (քույր) և «libros» (գրքեր) գոյականներին։',
        },
        {
          id: 'p2-q2',
          number: 2,
          type: 'multiple-choice',
          instructionEs: '¿Qué es «lentamente»?',
          instructionHy: 'Ի՞նչ է «lentamente» բառը՝',
          sentenceEs: 'Laura habla lentamente.',
          sentenceHy: 'Լաուրան խոսում է դանդաղ։',
          options: [
            { key: 'a', labelEs: 'Adjetivo', labelHy: 'Ածական' },
            { key: 'b', labelEs: 'Sustantivo', labelHy: 'Գոյական' },
            { key: 'c', labelEs: 'Adverbio', labelHy: 'Մակբայ' },
            { key: 'd', labelEs: 'Verbo', labelHy: 'Բայ' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) adverbio',
          correctAnswerHy: 'c) adverbio (մակբայ)',
          explanationEs: '«Lentamente» es un adverbio de modo terminado en -mente que modifica al verbo «habla».',
          explanationHy: 'Մակբայ է, որովհետև բնութագրում է «habla» (խոսում է) բայը։',
        },
        {
          id: 'p2-q3',
          number: 3,
          type: 'multiple-choice',
          instructionEs: '¿Qué categoría es «simpática»?',
          instructionHy: 'Ի՞նչ կարգ է «simpática» բառը՝',
          sentenceEs: 'Tenemos una profesora simpática.',
          sentenceHy: 'Մենք ունենք համակրելի ուսուցչուհի։',
          options: [
            { key: 'a', labelEs: 'Sustantivo', labelHy: 'Գոյական' },
            { key: 'b', labelEs: 'Adjetivo', labelHy: 'Ածական' },
            { key: 'c', labelEs: 'Verbo', labelHy: 'Բայ' },
            { key: 'd', labelEs: 'Pronombre', labelHy: 'Դերանուն' },
          ],
          correctOptionKey: 'b',
          correctAnswerText: 'b) adjetivo',
          correctAnswerHy: 'b) adjetivo (ածական)',
          explanationEs: '«Simpática» expresa una cualidad de «profesora», por lo que es adjetivo calificativo.',
          explanationHy: 'Ածական է. բնութագրում է «profesora» գոյականը։',
        },
        {
          id: 'p2-q4',
          number: 4,
          type: 'multiple-choice',
          instructionEs: '¿Qué es «pero» en la siguiente oración?',
          instructionHy: 'Ի՞նչ է «pero» բառը հետևյալ նախադասության մեջ՝',
          sentenceEs: 'Quiero salir, pero tengo que estudiar.',
          sentenceHy: 'Ուզում եմ դուրս գալ, բայց պետք է սովորեմ։',
          options: [
            { key: 'a', labelEs: 'Adverbio', labelHy: 'Մակբայ' },
            { key: 'b', labelEs: 'Determinante', labelHy: 'Որոշիչ' },
            { key: 'c', labelEs: 'Nexo', labelHy: 'Կապակցիչ / Շաղկապ' },
            { key: 'd', labelEs: 'Pronombre', labelHy: 'Դերանուն' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) nexo',
          correctAnswerHy: 'c) nexo (կապակցիչ)',
          explanationEs: '«Pero» es una conjunción coordinante que une dos oraciones.',
          explanationHy: 'Կապակցիչ է, որովհետև կապում է երկու գաղափար։',
        },
        {
          id: 'p2-q5',
          number: 5,
          type: 'multiple-choice',
          instructionEs: '¿Qué es «Nosotros»?',
          instructionHy: 'Ի՞նչ է «Nosotros» բառը՝',
          sentenceEs: 'Nosotros terminamos el ejercicio.',
          sentenceHy: 'Մենք ավարտեցինք վարժությունը։',
          options: [
            { key: 'a', labelEs: 'Pronombre', labelHy: 'Դերանուն' },
            { key: 'b', labelEs: 'Determinante', labelHy: 'Որոշիչ' },
            { key: 'c', labelEs: 'Sustantivo', labelHy: 'Գոյական' },
            { key: 'd', labelEs: 'Adverbio', labelHy: 'Մակբայ' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) pronombre',
          correctAnswerHy: 'a) pronombre (դերանուն)',
          explanationEs: '«Nosotros» es un pronombre personal que sustituye a los emisores del mensaje.',
          explanationHy: 'Անձնական դերանուն է (մենք)։',
        },
      ],
    },
    {
      id: 'p2-s2',
      sectionNumber: 2,
      titleEs: '2. Una palabra, diferentes funciones',
      titleHy: '2. Միևնույն բառը՝ տարբեր դերերով',
      descriptionEs: 'La misma palabra puede ser determinante o pronombre según si acompaña o sustituye al sustantivo.',
      descriptionHy: 'Միևնույն բառը կարող է լինել որոշիչ կամ դերանուն՝ կախված նրանից, թե ուղեկցո՞ւմ է, թե՞ փոխարինում գոյականին։',
      questions: [
        {
          id: 'p2-q6',
          number: 6,
          type: 'reasoning',
          instructionEs: '¿Qué es «este» en esta frase?',
          instructionHy: 'Ի՞նչ է «este»-ն այս նախադասության մեջ՝',
          sentenceEs: 'Este libro es interesante.',
          sentenceHy: 'Այս գիրքը հետաքրքիր է։',
          correctAnswerText: 'determinante, porque acompaña a libro.',
          correctAnswerHy: 'Որոշիչ է, որովհետև ուղեկցում է libro գոյականին։',
          explanationEs: '«Este» va justo antes de «libro», especificándolo → determinante demostrativo.',
          explanationHy: '«Este»-ն գտնվում է «libro» գոյականի կողքին և կոնկրետացնում է այն → որոշիչ։',
        },
        {
          id: 'p2-q7',
          number: 7,
          type: 'reasoning',
          instructionEs: '¿Qué es «este» en esta frase?',
          instructionHy: 'Ի՞նչ է «este»-ն այս նախադասության մեջ՝',
          sentenceEs: 'Este es interesante.',
          sentenceHy: 'Սա հետաքրքիր է։',
          correctAnswerText: 'pronombre, porque aparece solo y sustituye al sustantivo.',
          correctAnswerHy: 'Դերանուն է, որովհետև գոյականի փոխարեն է օգտագործվում։',
          explanationEs: '«Este» no acompaña a ningún sustantivo, toma el lugar del sujeto → pronombre demostrativo.',
          explanationHy: '«Este»-ն չի ուղեկցում որևէ գոյականի, այլ փոխարինում է նրան → դերանուն։',
        },
        {
          id: 'p2-q8',
          number: 8,
          type: 'reasoning',
          instructionEs: '¿Qué es «muchos» en esta frase?',
          instructionHy: 'Ի՞նչ է «muchos»-ը այս նախադասության մեջ՝',
          sentenceEs: 'Muchos alumnos llegaron.',
          sentenceHy: 'Շատ աշակերտներ եկան։',
          correctAnswerText: 'determinante, porque acompaña a alumnos.',
          correctAnswerHy: 'Որոշիչ է, որովհետև ուղեկցում է alumnos գոյականին։',
          explanationEs: '«Muchos» cuantifica al sustantivo «alumnos» → determinante indefinido.',
          explanationHy: 'Ուղեկցում է «alumnos» (աշակերտներ) գոյականին → որոշիչ։',
        },
        {
          id: 'p2-q9',
          number: 9,
          type: 'reasoning',
          instructionEs: '¿Qué es «muchos» en esta frase?',
          instructionHy: 'Ի՞նչ է «muchos»-ը այս նախադասության մեջ՝',
          sentenceEs: 'Muchos llegaron tarde.',
          sentenceHy: 'Շատերը ուշացած եկան։',
          correctAnswerText: 'pronombre, porque el sustantivo está ausente y lo sustituye.',
          correctAnswerHy: 'Դերանուն է, որովհետև գոյականը բացակայում է և muchos-ը փոխարինում է նրան։',
          explanationEs: 'No hay sustantivo; «muchos» ocupa el lugar del sujeto → pronombre indefinido.',
          explanationHy: 'Գոյական չկա, «muchos»-ը հանդես է գալիս որպես ենթակա → դերանուն։',
        },
      ],
    },
    {
      id: 'p2-s3',
      sectionNumber: 3,
      titleEs: '3. Encuentra todas las categorías',
      titleHy: '3. Գտի՛ր բոլոր քերականական կարգերը',
      descriptionEs: 'Analiza la oración compleja y clasifica todas sus palabras según su categoría.',
      descriptionHy: 'Վերլուծի՛ր բարդ նախադասությունը և բոլոր բառերը խմբավորի՛ր ըստ իրենց կարգերի։',
      questions: [
        {
          id: 'p2-q10',
          number: 10,
          type: 'word-by-word',
          instructionEs: 'Encuentra en la oración:',
          instructionHy: 'Նախադասության մեջ գտի՛ր հետևյալները՝',
          sentenceEs: 'Mis amigos nuevos estudian mucho porque mañana tienen un examen difícil.',
          sentenceHy: 'Իմ նոր ընկերները շատ են սովորում, որովհետև վաղը դժվար քննություն ունեն։',
          correctAnswerText: 'Determinantes: mis, un | Sustantivos: amigos, examen | Adjetivos: nuevos, difícil | Verbos: estudian, tienen | Adverbios: mucho, mañana | Nexo: porque',
          breakdown: [
            { word: 'Determinantes', category: 'mis, un', categoryHy: 'իմ, մի (որոշիչներ)' },
            { word: 'Sustantivos', category: 'amigos, examen', categoryHy: 'ընկերներ, քննություն (գոյականներ)' },
            { word: 'Adjetivos', category: 'nuevos, difícil', categoryHy: 'նոր, դժվար (ածականներ)' },
            { word: 'Verbos', category: 'estudian, tienen', categoryHy: 'սովորում են, ունեն (բայեր)' },
            { word: 'Adverbios', category: 'mucho, mañana', categoryHy: 'շատ, վաղը (մակբայներ)' },
            { word: 'Nexo', category: 'porque', categoryHy: 'որովհետև (կապակցիչ)' },
          ],
          explanationEs: 'Determinantes: mis (posesivo), un (artículo indeterminado). Sustantivos: amigos, examen. Adjetivos: nuevos, difícil. Verbos: estudian, tienen. Adverbios: mucho (cantidad), mañana (tiempo). Nexo: porque (causal).',
          explanationHy: 'Որոշիչներ՝ mis, un։ Գոյականներ՝ amigos, examen։ Ածականներ՝ nuevos, difícil։ Բայեր՝ estudian, tienen։ Մակբայներ՝ mucho, mañana։ Կապակցիչ՝ porque։',
        },
      ],
    },
    {
      id: 'p2-s4',
      sectionNumber: 4,
      titleEs: '4. Encuentra el error del alumno',
      titleHy: '4. Գտի՛ր աշակերտի սխալը',
      descriptionEs: 'Detecta y corrige el fallo común que comete un estudiante en el análisis gramatical.',
      descriptionHy: 'Գտի՛ր և ուղղի՛ր այն տարածված սխալը, որն արել է աշակերտը քերականական վերլուծության մեջ։',
      questions: [
        {
          id: 'p2-q11',
          number: 11,
          type: 'reasoning',
          instructionEs: '¿Qué error ha cometido el alumno en el análisis?',
          instructionHy: 'Ի՞նչ սխալ է թույլ տվել աշակերտը վերլուծության մեջ՝',
          sentenceEs: 'Frase: «Mi perro pequeño corre rápidamente.»\nAlumno: mi → pronombre, perro → sustantivo, pequeño → adjetivo, corre → verbo, rápidamente → adverbio.',
          sentenceHy: 'Նախադասություն՝ «Mi perro pequeño corre rápidamente.»\nԱշակերտ՝ mi → դերանուն, perro → գոյական, pequeño → ածական, corre → բայ, rápidamente → մակբայ։',
          correctAnswerText: '❌ mi → pronombre | ✅ mi → determinante',
          correctAnswerHy: '❌ mi → pronombre | ✅ mi → determinante (որոշիչ)',
          explanationEs: '«Mi» acompaña al sustantivo «perro», por lo que no es un pronombre sino un determinante posesivo.',
          explanationHy: '«mi»-ն որոշիչ է, որովհետև ուղեկցում է «perro» (շուն) գոյականին, այլ ոչ թե դերանուն։',
        },
        {
          id: 'p2-q12',
          number: 12,
          type: 'reasoning',
          instructionEs: 'Un alumno dice que en «Ella estudia mucho porque tiene examen», porque es adverbio. ¿Es correcto?',
          instructionHy: 'Աշակերտը ասում է, որ «porque»-ն մակբայ է։ Ճի՞շտ է արդյոք։',
          sentenceEs: 'Ella estudia mucho porque tiene examen. Alumno: porque → adverbio.',
          sentenceHy: 'Նա շատ է սովորում, որովհետև քննություն ունի։ Աշակերտ՝ porque → մակբայ։',
          correctAnswerText: '❌ Incorrecto. ✅ porque → nexo',
          correctAnswerHy: '❌ Սխալ է։ ✅ porque → nexo (կապակցիչ)',
          explanationEs: '«Porque» es una conjunción causal (nexo) que une la oración principal con la subordinada.',
          explanationHy: '«porque»-ն կապակցիչ (շաղկապ) է, որը կապում է երկու նախադասություն միմյանց։',
        },
        {
          id: 'p2-q13',
          number: 13,
          type: 'reasoning',
          instructionEs: 'Un alumno clasifica: «simpática → sustantivo». ¿Es correcto?',
          instructionHy: 'Աշակերտը դասակարգում է՝ «simpática → գոյական»։ Ճի՞շտ է։',
          sentenceEs: 'Una chica simpática llegó ayer. Alumno: simpática → sustantivo.',
          sentenceHy: 'Մի համակրելի աղջիկ եկավ երեկ։ Աշակերտ՝ simpática → գոյական։',
          correctAnswerText: '❌ Incorrecto. ✅ simpática → adjetivo',
          correctAnswerHy: '❌ Սխալ է։ ✅ simpática → adjetivo (ածական)',
          explanationEs: '«Simpática» expresa una cualidad del sustantivo chica, por lo tanto es un adjetivo.',
          explanationHy: 'Այն բնութագրում է «chica» (աղջիկ) գոյականը, հետևաբար ածական է։',
        },
      ],
    },
    {
      id: 'p2-s5',
      sectionNumber: 5,
      titleEs: '5. Elige dos respuestas relacionadas',
      titleHy: '5. Ընտրի՛ր ճիշտ զույգը',
      descriptionEs: 'Identifica la pareja de palabras que cumple la condición gramatical pedida.',
      descriptionHy: 'Ընտրի՛ր բառերի այն զույգը, որը համապատասխանում է նշված քերականական պայմանին։',
      questions: [
        {
          id: 'p2-q14',
          number: 14,
          type: 'multiple-choice',
          instructionEs: '¿Qué pareja contiene sustantivo + adjetivo?',
          instructionHy: 'Ո՞ր զույգն է պարունակում գոյական + ածական՝',
          options: [
            { key: 'a', labelEs: 'casa – grande', labelHy: 'տուն – մեծ' },
            { key: 'b', labelEs: 'rápidamente – ayer', labelHy: 'արագորեն – երեկ' },
            { key: 'c', labelEs: 'ella – nosotros', labelHy: 'նա – մենք' },
            { key: 'd', labelEs: 'pero – porque', labelHy: 'բայց – որովհետև' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) casa – grande',
          correctAnswerHy: 'a) casa (գոյական) – grande (ածական)',
          explanationEs: '«Casa» es sustantivo y «grande» es adjetivo.',
          explanationHy: '«casa»-ն գոյական է, իսկ «grande»-ն՝ ածական։',
        },
        {
          id: 'p2-q15',
          number: 15,
          type: 'multiple-choice',
          instructionEs: '¿Qué pareja contiene dos nexos?',
          instructionHy: 'Ո՞ր զույգն է պարունակում երկու կապակցիչ՝',
          options: [
            { key: 'a', labelEs: 'pero – porque', labelHy: 'բայց – որովհետև' },
            { key: 'b', labelEs: 'casa – escuela', labelHy: 'տուն – դպրոց' },
            { key: 'c', labelEs: 'tú – ella', labelHy: 'դու – նա' },
            { key: 'd', labelEs: 'hoy – nunca', labelHy: 'այսօր – երբեք' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) pero – porque',
          correctAnswerHy: 'a) pero – porque (երկուսն էլ կապակցիչ են)',
          explanationEs: '«Pero» y «porque» son conjunciones que funcionan como nexos oracionales.',
          explanationHy: 'Երկուսն էլ շաղկապներ / կապակցիչներ են։',
        },
        {
          id: 'p2-q16',
          number: 16,
          type: 'multiple-choice',
          instructionEs: '¿Qué pareja contiene dos adverbios?',
          instructionHy: 'Ո՞ր զույգն է պարունակում երկու մակբայ՝',
          options: [
            { key: 'a', labelEs: 'hoy – aquí', labelHy: 'այսօր – այստեղ' },
            { key: 'b', labelEs: 'mi – este', labelHy: 'իմ – այս' },
            { key: 'c', labelEs: 'bonito – grande', labelHy: 'գեղեցիկ – մեծ' },
            { key: 'd', labelEs: 'escribir – estudiar', labelHy: 'գրել – սովորել' },
          ],
          correctOptionKey: 'a',
          correctAnswerText: 'a) hoy – aquí',
          correctAnswerHy: 'a) hoy (այսօր) – aquí (այստեղ)',
          explanationEs: '«Hoy» (tiempo) y «aquí» (lugar) son ambos adverbios.',
          explanationHy: '«Hoy» (ժամանակ) և «aquí» (վայր) երկուսն էլ մակբայներ են։',
        },
      ],
    },
    {
      id: 'p2-s6',
      sectionNumber: 6,
      titleEs: '6. Completa con una palabra de la categoría indicada',
      titleHy: '6. Լրացրո՛ւ նշված քերականական կարգի բառով',
      descriptionEs: 'Completa el espacio en blanco con un término que pertenezca a la categoría solicitada.',
      descriptionHy: 'Լրացրո՛ւ բաց թողնված տեղը համապատասխան քերականական կարգի բառով։',
      questions: [
        {
          id: 'p2-q17',
          number: 17,
          type: 'fill-category',
          instructionEs: 'Completa con un Adjetivo:',
          instructionHy: 'Լրացրո՛ւ Ածականով՝',
          sentenceEs: 'El examen es __________.',
          sentenceHy: 'Քննությունը __________ է։',
          targetPromptEs: 'Adjetivo',
          targetPromptHy: 'Ածական',
          correctAnswerText: 'difícil (o: fácil, largo, importante, bueno)',
          correctAnswerHy: 'difícil (դժվար) կամ fácil, largo, importante',
          acceptableAnswers: ['difícil', 'dificil', 'fácil', 'facil', 'largo', 'importante', 'bueno'],
          explanationEs: 'Cualquier adjetivo válido que describa al examen es correcto (ej. difícil, fácil, interesante).',
          explanationHy: 'Ցանկացած ճիշտ ածական ընդունելի է (օր.՝ difícil, fácil, երկար, կարևոր)։',
        },
        {
          id: 'p2-q18',
          number: 18,
          type: 'fill-category',
          instructionEs: 'Completa con un Adverbio:',
          instructionHy: 'Լրացրո՛ւ Մակբայով՝',
          sentenceEs: 'Carlos corre __________.',
          sentenceHy: 'Կառլոսը վազում է __________։',
          targetPromptEs: 'Adverbio',
          targetPromptHy: 'Մակբայ',
          correctAnswerText: 'rápidamente (o: rápido, bien, mucho, siempre)',
          correctAnswerHy: 'rápidamente (արագորեն), bien (լավ), mucho (շատ)',
          acceptableAnswers: ['rápidamente', 'rapidamente', 'rápido', 'rapido', 'bien', 'mucho', 'lentamente'],
          explanationEs: 'Un adverbio de modo o cantidad encaja perfectamente (rápidamente, bien, mucho).',
          explanationHy: 'Ձևի կամ չափի մակբայ (օր.՝ rápidamente, bien, mucho)։',
        },
        {
          id: 'p2-q19',
          number: 19,
          type: 'fill-category',
          instructionEs: 'Completa con un Nexo:',
          instructionHy: 'Լրացրո՛ւ Կապակցիչով՝',
          sentenceEs: 'Quiero ir al parque, __________ está lloviendo.',
          sentenceHy: 'Ուզում եմ գնալ զբոսայգի, __________ անձրև է գալիս։',
          targetPromptEs: 'Nexo',
          targetPromptHy: 'Կապակցիչ',
          correctAnswerText: 'pero',
          correctAnswerHy: 'pero (բայց)',
          acceptableAnswers: ['pero', 'aunque'],
          explanationEs: '«Pero» o «aunque» son nexos adversativos que expresan contraste.',
          explanationHy: '«pero» (բայց) կամ «aunque» (թեև) կապակցիչներն են համապատասխանում։',
        },
        {
          id: 'p2-q20',
          number: 20,
          type: 'fill-category',
          instructionEs: 'Completa con un Determinante:',
          instructionHy: 'Լրացրո՛ւ Որոշիչով՝',
          sentenceEs: '__________ mochila está en clase.',
          sentenceHy: '__________ պայուսակը դասարանում է։',
          targetPromptEs: 'Determinante',
          targetPromptHy: 'Որոշիչ',
          correctAnswerText: 'Mi (o: Esta, La, Tu, Su)',
          correctAnswerHy: 'Mi (իմ), Esta (այս), La (որոշյալ հոդ)',
          acceptableAnswers: ['Mi', 'mi', 'Esta', 'esta', 'La', 'la', 'Tu', 'tu', 'Su', 'su'],
          explanationEs: 'Determinantes válidos: posesivos (Mi, Tu, Su), demostrativos (Esta, Aquella) o artículos (La).',
          explanationHy: 'Համապատասխանում է ստացական (Mi, Tu), ցուցական (Esta) կամ հոդ (La)։',
        },
        {
          id: 'p2-q21',
          number: 21,
          type: 'fill-category',
          instructionEs: 'Completa con un Pronombre:',
          instructionHy: 'Լրացրո՛ւ Դերանունով՝',
          sentenceEs: 'María está cansada. __________ quiere descansar.',
          sentenceHy: 'Մարիան հոգնած է։ __________ ուզում է հանգստանալ։',
          targetPromptEs: 'Pronombre',
          targetPromptHy: 'Դերանուն',
          correctAnswerText: 'Ella',
          correctAnswerHy: 'Ella (նա)',
          acceptableAnswers: ['Ella', 'ella'],
          explanationEs: 'El pronombre «Ella» sustituye a María en la segunda oración.',
          explanationHy: '«Ella» դերանունը փոխարինում է Մարիային։',
        },
        {
          id: 'p2-q22',
          number: 22,
          type: 'fill-category',
          instructionEs: 'Completa con un Verbo:',
          instructionHy: 'Լրացրո՛ւ Բայով՝',
          sentenceEs: 'Los alumnos __________ para el examen.',
          sentenceHy: 'Աշակերտները քննության համար __________։',
          targetPromptEs: 'Verbo',
          targetPromptHy: 'Բայ',
          correctAnswerText: 'estudian (o: repasan, leen, se preparan)',
          correctAnswerHy: 'estudian (սովորում են) կամ repasan, se preparan',
          acceptableAnswers: ['estudian', 'repasan', 'leen', 'practican', 'estudiaron'],
          explanationEs: 'Verbos en tercera persona del plural como «estudian» o «repasan».',
          explanationHy: 'Հոգնակի 3-րդ դեմքի բայ՝ «estudian» (սովորում են) կամ «repasan»։',
        },
      ],
    },
    {
      id: 'p2-s7',
      sectionNumber: 7,
      titleEs: '7. Sustituye sin cambiar el significado principal',
      titleHy: '7. Փոխարինի՛ր՝ պահպանելով հիմնական իմաստը',
      descriptionEs: 'Sustituye el sujeto por el pronombre correspondiente.',
      descriptionHy: 'Ենթական փոխարինի՛ր համապատասխան դերանունով՝ պահպանելով նախադասության իմաստը։',
      questions: [
        {
          id: 'p2-q23',
          number: 23,
          type: 'replace-pronoun',
          instructionEs: 'Sustituye «Carlos» por un pronombre:',
          instructionHy: '«Carlos»-ը փոխարինի՛ր դերանունով՝',
          sentenceEs: 'Carlos juega al fútbol.',
          sentenceHy: 'Կառլոսը ֆուտբոլ է խաղում։',
          targetPromptEs: 'Sustituye «Carlos» por un pronombre.',
          targetPromptHy: 'Carlos-ը փոխարինի՛ր դերանունով։',
          correctAnswerText: 'Él juega al fútbol.',
          correctAnswerHy: 'Él juega al fútbol. (Նա ֆուտբոլ է խաղում։)',
          acceptableAnswers: ['Él', 'él', 'El', 'Él juega al fútbol.', 'el juega al futbol'],
          explanationEs: 'Carlos → 3ª persona del singular masculino → «Él» (con tilde).',
          explanationHy: 'Կառլոս → եզակի 3-րդ դեմք արական → «Él» (շեշտով)։',
        },
        {
          id: 'p2-q24',
          number: 24,
          type: 'replace-pronoun',
          instructionEs: 'Sustituye «Ana y María» por un pronombre:',
          instructionHy: '«Ana y María»-ն փոխարինի՛ր դերանունով՝',
          sentenceEs: 'Ana y María estudian juntas.',
          sentenceHy: 'Անան և Մարիան միասին են սովորում։',
          targetPromptEs: 'Sustituye «Ana y María» por un pronombre.',
          targetPromptHy: 'Ana y María-ն փոխարինի՛ր դերանունով։',
          correctAnswerText: 'Ellas estudian juntas.',
          correctAnswerHy: 'Ellas estudian juntas. (Նրանք միասին են սովորում։)',
          acceptableAnswers: ['Ellas', 'ellas', 'Ellas estudian juntas.'],
          explanationEs: 'Ana y María son 3ª persona plural femenino → «Ellas».',
          explanationHy: 'Երկու աղջիկ (հոգնակի 3-րդ դեմք իգական) → «Ellas» (նրանք)։',
        },
        {
          id: 'p2-q25',
          number: 25,
          type: 'replace-pronoun',
          instructionEs: 'Sustituye «Pedro y yo» por un pronombre:',
          instructionHy: '«Pedro y yo»-ն փոխարինի՛ր դերանունով՝',
          sentenceEs: 'Pedro y yo vamos al colegio.',
          sentenceHy: 'Պեդրոն և ես գնում ենք դպրոց։',
          targetPromptEs: 'Sustituye «Pedro y yo» por un pronombre.',
          targetPromptHy: 'Pedro y yo-ն փոխարինի՛ր դերանունով։',
          correctAnswerText: 'Nosotros vamos al colegio.',
          correctAnswerHy: 'Nosotros vamos al colegio. (Մենք գնում ենք դպրոց։)',
          acceptableAnswers: ['Nosotros', 'nosotros', 'Nosotros vamos al colegio.'],
          explanationEs: 'Pedro y yo incluye la 1ª persona → «Nosotros».',
          explanationHy: 'Պեդրոն և ես → 1-ին դեմք հոգնակի → «Nosotros» (մենք)։',
        },
      ],
    },
    {
      id: 'p2-s8',
      sectionNumber: 8,
      titleEs: '8. Texto tipo examen',
      titleHy: '8. Տեքստ՝ քննության ձևաչափով',
      descriptionEs: 'Lee el texto y extrae las palabras de las categorías solicitadas.',
      descriptionHy: 'Կարդա՛ տեքստը և դուրս գրի՛ր պահանջված քերականական կարգերի բառերը։',
      contextEs: 'Esta mañana, mi compañero Daniel llegó bastante temprano al colegio. Él llevaba una mochila nueva y grande, pero parecía cansado. Después entró rápidamente en nuestra clase porque tenía un examen importante.',
      contextHy: 'Այս առավոտ իմ դասընկեր Դանիելը բավական շուտ հասավ դպրոց։ Նա նոր և մեծ պայուսակ ուներ, բայց հոգնած էր թվում։ Հետո արագ մտավ մեր դասարան, որովհետև կարևոր քննություն ուներ։',
      questions: [
        {
          id: 'p2-q26',
          number: 26,
          type: 'text-analysis',
          instructionEs: 'Busca tres sustantivos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երեք գոյական՝',
          sentenceEs: 'Busca tres sustantivos.',
          sentenceHy: 'Գտի՛ր երեք գոյական։',
          correctAnswerText: 'compañero, mochila, colegio (o: clase, examen, Daniel)',
          correctAnswerHy: 'compañero, mochila, colegio (կամ clase, examen, Daniel)',
          explanationEs: 'Sustantivos válidos: mañana, compañero, Daniel, colegio, mochila, clase, examen.',
          explanationHy: 'Գոյականներ՝ mañana, compañero, Daniel, colegio, mochila, clase, examen։',
        },
        {
          id: 'p2-q27',
          number: 27,
          type: 'text-analysis',
          instructionEs: 'Busca tres adjetivos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երեք ածական՝',
          sentenceEs: 'Busca tres adjetivos.',
          sentenceHy: 'Գտի՛ր երեք ածական։',
          correctAnswerText: 'nueva, grande, cansado (o: importante)',
          correctAnswerHy: 'nueva (նոր), grande (մեծ), cansado (հոգնած), importante (կարևոր)',
          explanationEs: 'Adjetivos del texto: nueva, grande (describen mochila); cansado (estado); importante (describe examen).',
          explanationHy: 'Ածականներ՝ nueva, grande, cansado, importante։',
        },
        {
          id: 'p2-q28',
          number: 28,
          type: 'text-analysis',
          instructionEs: 'Busca tres verbos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երեք բայ՝',
          sentenceEs: 'Busca tres verbos.',
          sentenceHy: 'Գտի՛ր երեք բայ։',
          correctAnswerText: 'llegó, llevaba, parecía (o: entró, tenía)',
          correctAnswerHy: 'llegó (հասավ), llevaba (կրում էր), parecía (թվում էր), entró (մտավ), tenía (ուներ)',
          explanationEs: 'Formas verbales: llegó, llevaba, parecía, entró, tenía.',
          explanationHy: 'Բայական ձևեր՝ llegó, llevaba, parecía, entró, tenía։',
        },
        {
          id: 'p2-q29',
          number: 29,
          type: 'text-analysis',
          instructionEs: 'Busca tres adverbios en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երեք մակբայ՝',
          sentenceEs: 'Busca tres adverbios.',
          sentenceHy: 'Գտի՛ր երեք մակբայ։',
          correctAnswerText: 'bastante, temprano, rápidamente (o: después, esta mañana)',
          correctAnswerHy: 'bastante (բավական), temprano (շուտ), rápidamente (արագորեն), después (հետո)',
          explanationEs: 'Adverbios: bastante (cantidad), temprano (tiempo), después (tiempo), rápidamente (modo).',
          explanationHy: 'Մակբայներ՝ bastante, temprano, después, rápidamente։',
        },
        {
          id: 'p2-q30',
          number: 30,
          type: 'text-analysis',
          instructionEs: 'Busca dos nexos en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երկու կապակցիչ՝',
          sentenceEs: 'Busca dos nexos.',
          sentenceHy: 'Գտի՛ր երկու կապակցիչ։',
          correctAnswerText: 'pero, porque (y «y»)',
          correctAnswerHy: 'pero (բայց), porque (որովհետև), y (և)',
          explanationEs: 'Nexos coordinantes y subordinantes: «pero», «porque», «y».',
          explanationHy: 'Կապակցիչներ՝ «pero», «porque», «y»։',
        },
        {
          id: 'p2-q31',
          number: 31,
          type: 'text-analysis',
          instructionEs: 'Busca un pronombre en el texto:',
          instructionHy: 'Տեքստից գտի՛ր մեկ դերանուն՝',
          sentenceEs: 'Busca un pronombre.',
          sentenceHy: 'Գտի՛ր մեկ դերանուն։',
          correctAnswerText: 'Él',
          correctAnswerHy: 'Él (նա)',
          acceptableAnswers: ['Él', 'él'],
          explanationEs: '«Él» es el pronombre personal que sustituye a Daniel.',
          explanationHy: '«Él»-ը անձնական դերանուն է, որը փոխարինում է Դանիելին։',
        },
        {
          id: 'p2-q32',
          number: 32,
          type: 'text-analysis',
          instructionEs: 'Busca tres determinantes en el texto:',
          instructionHy: 'Տեքստից գտի՛ր երեք որոշիչ՝',
          sentenceEs: 'Busca tres determinantes.',
          sentenceHy: 'Գտի՛ր երեք որոշիչ։',
          correctAnswerText: 'mi, una, nuestra (o: un, esta)',
          correctAnswerHy: 'mi (իմ), una (մի), nuestra (մեր), un, esta',
          explanationEs: 'Determinantes: esta (mañana), mi (compañero), una (mochila), nuestra (clase), un (examen).',
          explanationHy: 'Որոշիչներ՝ esta, mi, una, nuestra, un։',
        },
      ],
    },
    {
      id: 'p2-s9',
      sectionNumber: 9,
      titleEs: '9. ¿Qué palabra estoy describiendo?',
      titleHy: '9. Ո՞ր քերականական կարգն եմ նկարագրում',
      descriptionEs: 'Adivina la categoría gramatical a partir de su definición y ejemplos característicos.',
      descriptionHy: 'Գուշակի՛ր քերականական կարգը՝ ըստ նրա սահմանման և բնորոշ օրինակների։',
      questions: [
        {
          id: 'p2-q33',
          number: 33,
          type: 'reasoning',
          instructionEs: '¿Qué categoría gramatical soy?',
          instructionHy: 'Ո՞ր քերականական կարգն եմ ես՝',
          sentenceEs: '«Acompaño normalmente a un sustantivo: mi casa, este libro, dos amigos.»',
          sentenceHy: '«Սովորաբար ուղեկցում եմ գոյականին՝ mi casa, este libro, dos amigos:»',
          correctAnswerText: 'Determinante',
          correctAnswerHy: 'Determinante (Որոշիչ)',
          explanationEs: 'Va siempre con el sustantivo concretándolo en género, número, posesión o distancia.',
          explanationHy: 'Միշտ ուղեկցում է գոյականին և ճշտում նրա իմաստը → Որոշիչ։',
        },
        {
          id: 'p2-q34',
          number: 34,
          type: 'reasoning',
          instructionEs: '¿Qué categoría gramatical soy?',
          instructionHy: 'Ո՞ր քերականական կարգն եմ ես՝',
          sentenceEs: '«Puedo sustituir a una persona o cosa: él, ella, nosotros.»',
          sentenceHy: '«Կարող եմ փոխարինել անձին կամ առարկային՝ él, ella, nosotros:»',
          correctAnswerText: 'Pronombre',
          correctAnswerHy: 'Pronombre (Դերանուն)',
          explanationEs: 'El pronombre sustituye al nombre o sintagma nominal.',
          explanationHy: 'Փոխարինում է գոյականին → Դերանուն։',
        },
        {
          id: 'p2-q35',
          number: 35,
          type: 'reasoning',
          instructionEs: '¿Qué categoría gramatical soy?',
          instructionHy: 'Ո՞ր քերականական կարգն եմ ես՝',
          sentenceEs: '«Uno palabras u oraciones: pero, porque, y.»',
          sentenceHy: '«Կապում եմ բառեր կամ նախադասություններ՝ pero, porque, y:»',
          correctAnswerText: 'Nexo',
          correctAnswerHy: 'Nexo (Կապակցիչ / Շաղկապ)',
          explanationEs: 'Los nexos o conjunciones enlazan unidades lingüísticas.',
          explanationHy: 'Կապում է լեզվական միավորները → Կապակցիչ (nexo)։',
        },
        {
          id: 'p2-q36',
          number: 36,
          type: 'reasoning',
          instructionEs: '¿Qué categoría gramatical soy?',
          instructionHy: 'Ո՞ր քերականական կարգն եմ ես՝',
          sentenceEs: '«Puedo indicar tiempo, lugar, cantidad o modo: hoy, aquí, mucho, bien.»',
          sentenceHy: '«Կարող եմ ցույց տալ ժամանակ, վայր, քանակ կամ ձև՝ hoy, aquí, mucho, bien:»',
          correctAnswerText: 'Adverbio',
          correctAnswerHy: 'Adverbio (Մակբայ)',
          explanationEs: 'Los adverbios son palabras invariables que indican circunstancias.',
          explanationHy: 'Անփոփոխ բառեր, որոնք ցույց են տալիս հանգամանքներ → Մակբայ։',
        },
      ],
    },
    {
      id: 'p2-s10',
      sectionNumber: 10,
      titleEs: '10. Preguntas más parecidas al examen',
      titleHy: '10. Ավելի շատ քննության նման',
      descriptionEs: 'Reactivos frecuentes de control final de 1º ESO.',
      descriptionHy: '1º ESO մակարդակի վերջնական ստուգման ամենահաճախ հանդիպող հարցերը։',
      questions: [
        {
          id: 'p2-q37',
          number: 37,
          type: 'multiple-choice',
          instructionEs: 'En «Mis dos amigos llegaron ayer», ¿cuántos determinantes acompañan a «amigos»?',
          instructionHy: '«Mis dos amigos llegaron ayer» նախադասության մեջ քանի՞ որոշիչ է ուղեկցում «amigos» գոյականին՝',
          sentenceEs: 'Mis dos amigos llegaron ayer.',
          sentenceHy: 'Իմ երկու ընկերները եկան երեկ։',
          options: [
            { key: 'a', labelEs: '0', labelHy: '0' },
            { key: 'b', labelEs: '1', labelHy: '1' },
            { key: 'c', labelEs: '2 (mis, dos)', labelHy: '2 (mis, dos)' },
            { key: 'd', labelEs: '3', labelHy: '3' },
          ],
          correctOptionKey: 'c',
          correctAnswerText: 'c) 2 — mis, dos',
          correctAnswerHy: 'c) 2 — mis (իմ), dos (երկու)',
          explanationEs: '«Mis» es determinante posesivo y «dos» es determinante numeral cardinal.',
          explanationHy: '«Mis»-ը ստացական որոշիչ է, իսկ «dos»-ը՝ քանակական թվական որոշիչ։ Երկուսն էլ ուղեկցում են «amigos»-ին։',
        },
        {
          id: 'p2-q38',
          number: 38,
          type: 'word-by-word',
          instructionEs: 'En «Ella canta muy bien», identifica las categorías:',
          instructionHy: '«Ella canta muy bien» նախադասության մեջ որոշի՛ր կարգերը՝',
          sentenceEs: 'Ella canta muy bien.',
          sentenceHy: 'Նա շատ լավ է երգում։',
          correctAnswerText: 'Ella → pronombre, canta → verbo, muy → adverbio, bien → adverbio',
          breakdown: [
            { word: 'Ella', category: 'pronombre', categoryHy: 'դերանուն' },
            { word: 'canta', category: 'verbo', categoryHy: 'բայ' },
            { word: 'muy', category: 'adverbio', categoryHy: 'մակբայ (քանակի)' },
            { word: 'bien', category: 'adverbio', categoryHy: 'մակբայ (ձևի)' },
          ],
          explanationEs: '«Ella» pronombre personal; «canta» verbo cantar; «muy» adverbio que modifica a «bien»; «bien» adverbio de modo que modifica a «canta».',
          explanationHy: '«Ella» դերանուն է, «canta» բայ է, «muy» և «bien» մակբայներ են։',
        },
        {
          id: 'p2-q39',
          number: 39,
          type: 'reasoning',
          instructionEs: 'En «El chico alto corre rápido», ¿qué palabra describe al sustantivo chico?',
          instructionHy: '«El chico alto corre rápido» նախադասության մեջ ո՞ր բառն է նկարագրում «chico» գոյականին՝',
          sentenceEs: 'El chico alto corre rápido.',
          sentenceHy: 'Բարձրահասակ տղան արագ է վազում։',
          correctAnswerText: 'alto → adjetivo',
          correctAnswerHy: 'alto → adjetivo (ածական)',
          explanationEs: '«Alto» es el adjetivo que califica a «chico». (Ojo: «rápido» modifica al verbo correr, por lo que actúa como adverbio).',
          explanationHy: '«alto» ածականը բնութագրում է «chico» գոյականը։ (Իսկ «rápido»-ն լրացնում է «corre» բային և մակբայ է)։',
        },
        {
          id: 'p2-q40',
          number: 40,
          type: 'reasoning',
          instructionEs: 'En «No fui al parque porque llovía», ¿qué palabra une las dos ideas?',
          instructionHy: '«No fui al parque porque llovía» նախադասության մեջ ո՞ր բառն է միացնում երկու միտքը՝',
          sentenceEs: 'No fui al parque porque llovía.',
          sentenceHy: 'Ես չգնացի զբոսայգի, որովհետև անձրև էր գալիս։',
          correctAnswerText: 'porque → nexo',
          correctAnswerHy: 'porque → nexo (կապակցիչ)',
          explanationEs: '«Porque» es la conjunción / nexo causal que enlaza ambas cláusulas.',
          explanationHy: '«porque» (որովհետև) բառը կապակցիչ է։',
        },
      ],
    },
    {
      id: 'p2-s11',
      sectionNumber: 11,
      titleEs: '11. Reto final — Analiza tú solo',
      titleHy: '11. Վերջնական առաջադրանք — Ինքդ վերլուծի՛ր',
      descriptionEs: '¡El reto maestro! Analiza todas y cada una de las 10 palabras de esta oración compleja.',
      descriptionHy: 'Գլխավոր մարտահրավեր։ Վերլուծի՛ր այս բարդ նախադասության բոլոր 10 բառերը մեկ առ մեկ։',
      questions: [
        {
          id: 'p2-q41',
          number: 'Reto',
          type: 'word-by-word',
          instructionEs: 'Clasifica las 10 palabras de la oración:',
          instructionHy: 'Դասակարգի՛ր նախադասության բոլոր 10 բառերը՝',
          sentenceEs: 'Aquellos alumnos jóvenes estudian bastante, pero ellos también practican deporte.',
          sentenceHy: 'Այն երիտասարդ աշակերտները բավական շատ են սովորում, բայց նրանք նաև սպորտով են զբաղվում։',
          correctAnswerText: 'Aquellos → determinante | alumnos → sustantivo | jóvenes → adjetivo | estudian → verbo | bastante → adverbio | pero → nexo | ellos → pronombre | también → adverbio | practican → verbo | deporte → sustantivo',
          breakdown: [
            { word: 'Aquellos', category: 'determinante', categoryHy: 'որոշիչ (ցուցական)' },
            { word: 'alumnos', category: 'sustantivo', categoryHy: 'գոյական' },
            { word: 'jóvenes', category: 'adjetivo', categoryHy: 'ածական' },
            { word: 'estudian', category: 'verbo', categoryHy: 'բայ' },
            { word: 'bastante', category: 'adverbio', categoryHy: 'մակբայ (քանակի)' },
            { word: 'pero', category: 'nexo', categoryHy: 'կապակցիչ (հակադրական)' },
            { word: 'ellos', category: 'pronombre', categoryHy: 'դերանուն (անձնական)' },
            { word: 'también', category: 'adverbio', categoryHy: 'մակբայ (հաստատական)' },
            { word: 'practican', category: 'verbo', categoryHy: 'բայ' },
            { word: 'deporte', category: 'sustantivo', categoryHy: 'գոյական' },
          ],
          explanationEs: 'Esta oración contiene las 7 categorías gramaticales principales de 1º ESO en perfecta armonía sintáctica.',
          explanationHy: 'Այս նախադասությունը ներառում է 1º ESO-ի բոլոր 7 քերականական կարգերը կատարյալ ներդաշնակությամբ։',
        },
      ],
    },
  ],
};
