import { CategoryInfo } from './types';

export const GRAMMATICAL_CATEGORIES: CategoryInfo[] = [
  {
    id: 'sustantivo',
    nameEs: 'Sustantivo',
    nameHy: 'Գոյական',
    defEs: 'Nombra personas, animales, lugares, objetos o ideas.',
    defHy: 'Անվանում է մարդկանց, կենդանիներին, վայրերը, առարկաները կամ գաղափարները։',
    examplesEs: ['casa', 'alumno', 'libertad', 'perro', 'colegio'],
    color: 'emerald',
    icon: '🏛️',
  },
  {
    id: 'adjetivo',
    nameEs: 'Adjetivo',
    nameHy: 'Ածական',
    defEs: 'Expresa una cualidad o característica del sustantivo.',
    defHy: 'Ցույց է տալիս գոյականի հատկանիշը կամ որակը։',
    examplesEs: ['grande', 'bonito', 'rápido', 'nuevo', 'difícil'],
    color: 'blue',
    icon: '✨',
  },
  {
    id: 'verbo',
    nameEs: 'Verbo',
    nameHy: 'Բայ',
    defEs: 'Expresa acción, estado o proceso en un tiempo determinado.',
    defHy: 'Արտահայտում է գործողություն, վիճակ կամ ընթացք։',
    examplesEs: ['estudiar', 'correr', 'ser', 'juega', 'tienen'],
    color: 'amber',
    icon: '⚡',
  },
  {
    id: 'adverbio',
    nameEs: 'Adverbio',
    nameHy: 'Մակբայ',
    defEs: 'Modifica un verbo, un adjetivo u otro adverbio (tiempo, lugar, modo, cantidad).',
    defHy: 'Լրացնում կամ փոփոխում է բայի, ածականի կամ մեկ այլ մակբայի իմաստը։',
    examplesEs: ['hoy', 'muy', 'rápidamente', 'aquí', 'bastante'],
    color: 'purple',
    icon: '🧭',
  },
  {
    id: 'nexo',
    nameEs: 'Nexo',
    nameHy: 'Կապակցիչ / Շաղկապ',
    defEs: 'Une palabras, sintagmas u oraciones coordinadas o subordinadas.',
    defHy: 'Կապում է բառեր կամ նախադասություններ միմյանց հետ։',
    examplesEs: ['y', 'pero', 'porque', 'aunque', 'o'],
    color: 'rose',
    icon: '🔗',
  },
  {
    id: 'pronombre',
    nameEs: 'Pronombre',
    nameHy: 'Դերանուն',
    defEs: 'Sustituye a un sustantivo y no va acompañado de este.',
    defHy: 'Փոխարինում է գոյականին և հանդես է գալիս առանձին։',
    examplesEs: ['yo', 'tú', 'él', 'ella', 'nosotros', 'ellos'],
    color: 'indigo',
    icon: '👤',
  },
  {
    id: 'determinante',
    nameEs: 'Determinante',
    nameHy: 'Որոշիչ',
    defEs: 'Acompaña siempre al sustantivo y lo concreta (artículos, posesivos, demostrativos, numerales).',
    defHy: 'Ուղեկցում է գոյականին և ճշտում նրա իմաստը։',
    examplesEs: ['el', 'la', 'una', 'mi', 'este', 'dos', 'sus'],
    color: 'teal',
    icon: '🎯',
  },
];
